(load "src/turtle")
(load "src/svg")
(setf *random-state* (make-random-state t))

(defparameter width 1500)
(defparameter height 1500)

(defun rad-deg (r)
  (/ (* r 180.0) pi))

(defun calc-triangle (size adja)
  (let* ((adjb (sqrt (- (* size size) (* adja adja))))
         (theta (rad-deg (acos (/ adja size)))))
    (list adjb theta)))

(defun trunk (size turtle)
  (if (> size 10)
    (let* ((alea (random (* size 0.1)))
           (adja (+ (* (/ size 2.0) (sqrt 2.0)) alea))
           (calc (calc-triangle size adja))
           (adjb (car calc))
           (theta (cadr calc)))
      (execute `(
                 (DOWN)
                 (FORWARD ,size)
                 (RIGHT 90)
                 (FORWARD ,size)
                 (RIGHT 90)
                 (FORWARD ,size)
                 (RIGHT 90)
                 (FORWARD ,size)
                 (RIGHT 90)
                 (UP)
                 (FORWARD ,size)
                 (PUSH-STATE)
                 (DOWN)
                 (RIGHT ,theta)
                 (FORWARD ,adjb)
                 (PUSH-STATE)
                 (RIGHT 90)
                 (FORWARD ,adja)
                 (UP)
                 (POP-STATE)
                 (RUN ,(lambda (tu)
                          (trunk adja tu)))
                 (UP)
                 (POP-STATE)
                 (RIGHT ,theta)
                 (LEFT 90)
                 (RUN ,(lambda (tu)
                         (trunk adjb tu)))
                 ) turtle))
    turtle))

(defun main ()
    (let ((f-turtle (trunk 200.0 (left 90 (goto '(500.0 500.0) (new-turtle))))))
      (format t 
              (render-svg width height (calibrate (lines f-turtle))))))

(main)
(sb-ext:quit)

