(load "src/turtle")
(load "src/svg")

(setf *random-state* (make-random-state t))

(defparameter width 1500)
(defparameter height 1500)
(defparameter square-size 100)

(defun triangle (size turtle)
  (let ((dist (/ size 3.0)))
    (execute `(
               (DOWN)
               (FORWARD ,dist)
               (RIGHT 120)
               (FORWARD ,dist)
               (RIGHT 120)
               (FORWARD ,dist)
               (RIGHT 120)
               (UP)
               ) turtle)))

(defun square (size turtle)
  (let ((dist (/ size 4.0)))
    (execute `(
               (DOWN)
               (FORWARD ,dist)
               (RIGHT 90)
               (FORWARD ,dist)
               (RIGHT 90)
               (FORWARD ,dist)
               (RIGHT 90)
               (FORWARD ,dist)
               (RIGHT 90)
               (UP)
               ) turtle)))

(defun pentagon (size turtle)
  (let ((dist (/ size 5.0)))
    (execute `(
               (DOWN)
               (FORWARD ,dist)
               (RIGHT 72)
               (FORWARD ,dist)
               (RIGHT 72)
               (FORWARD ,dist)
               (RIGHT 72)
               (FORWARD ,dist)
               (RIGHT 72)
               (FORWARD ,dist)
               (RIGHT 72)
               (UP)
               ) turtle)))

(defun hexagon (size turtle)
  (let ((dist (/ size 6.0)))
    (execute `(
               (DOWN)
               (FORWARD ,dist)
               (RIGHT 60)
               (FORWARD ,dist)
               (RIGHT 60)
               (FORWARD ,dist)
               (RIGHT 60)
               (FORWARD ,dist)
               (RIGHT 60)
               (FORWARD ,dist)
               (RIGHT 60)
               (FORWARD ,dist)
               (RIGHT 60)
               (UP)
               ) turtle)))

(defparameter hepta (/ 360.0 7.0))
(defun heptagon (size turtle)
  (let ((dist (/ size 7.0)))
    (execute `(
               (DOWN)
               (FORWARD ,dist)
               (RIGHT ,hepta)
               (FORWARD ,dist)
               (RIGHT ,hepta)
               (FORWARD ,dist)
               (RIGHT ,hepta)
               (FORWARD ,dist)
               (RIGHT ,hepta)
               (FORWARD ,dist)
               (RIGHT ,hepta)
               (FORWARD ,dist)
               (RIGHT ,hepta)
               (FORWARD ,dist)
               (RIGHT ,hepta)
               (UP)
               ) turtle)))

(defun octogon (size turtle)
  (let ((dist (/ size 8.0)))
    (execute `(
               (DOWN)
               (FORWARD ,dist)
               (RIGHT 45)
               (FORWARD ,dist)
               (RIGHT 45)
               (FORWARD ,dist)
               (RIGHT 45)
               (FORWARD ,dist)
               (RIGHT 45)
               (FORWARD ,dist)
               (RIGHT 45)
               (FORWARD ,dist)
               (RIGHT 45)
               (FORWARD ,dist)
               (RIGHT 45)
               (FORWARD ,dist)
               (RIGHT 45)
               (UP)
               ) turtle)))

(defun shape (selector size turtle)
  (cond
    ((eq selector 0) (triangle size turtle))
    ((eq selector 1) (square size turtle))
    ((eq selector 2) (pentagon size turtle))
    ((eq selector 3) (hexagon size turtle))
    ((eq selector 4) (heptagon size turtle))
    (t (octogon size turtle))))


(defun random-squares (n turtle)
  (if (eq 0 n)
    turtle
    (let* ((angle (random 360))
           (factor (* 1.5 (+ (random 3) 1)))
           (dist (* factor (- (random 5) 25)))
           (size (+ 15 (* 45 (random 3))))
           (selector (random 6))
           (n-turtle (forward dist (turn angle turtle))))
      (cond
        ((< (x n-turtle) 0) (random-squares (- n 1) turtle))
        ((>= (x n-turtle) width) (random-squares (- n 1) turtle))
        ((< (y n-turtle) 0) (random-squares (- n 1) turtle))
        ((>= (y turtle) height) (random-squares (- n 1) turtle))
        (t (random-squares (- n 1)
                           (shape 5 size
                                  (down
                                    (forward dist
                                             (turn angle (up turtle)))))))))))
(defun main ()
  (let ((f-turtle
          (random-squares 1000
                          (goto '(750.0 750.0)
                                (new-turtle)))))
    (format t
            (render-svg width height (lines f-turtle)))))

(main)
(sb-ext:quit)
